--------------------------------------------------------
--  File created - воскресенье-февраля-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "MYUSER"."DEPARTMENTS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"CITYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MYUSER.DEPARTMENTS
SET DEFINE OFF;
Insert into MYUSER.DEPARTMENTS (ID,NAME,CITYID) values ('1','Отдел продаж','1');
Insert into MYUSER.DEPARTMENTS (ID,NAME,CITYID) values ('2','Отдел разработки','2');
Insert into MYUSER.DEPARTMENTS (ID,NAME,CITYID) values ('3','Отдел управления','3');
--------------------------------------------------------
--  DDL for Index SYS_C008321
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYUSER"."SYS_C008321" ON "MYUSER"."DEPARTMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008322
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYUSER"."SYS_C008322" ON "MYUSER"."DEPARTMENTS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger DEPARTMENTS_BEFOREINSERT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MYUSER"."DEPARTMENTS_BEFOREINSERT" 
BEFORE INSERT ON Departments
FOR EACH ROW
BEGIN
    SELECT Departments_Seq.NEXTVAL INTO :NEW.ID FROM dual;
END;
/
ALTER TRIGGER "MYUSER"."DEPARTMENTS_BEFOREINSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "MYUSER"."DEPARTMENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MYUSER"."DEPARTMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MYUSER"."DEPARTMENTS" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "MYUSER"."DEPARTMENTS" ADD FOREIGN KEY ("CITYID")
	  REFERENCES "MYUSER"."CITYDICTIONARY" ("ID") ENABLE;
