--------------------------------------------------------
--  File created - воскресенье-февраля-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "MYUSER"."EMPLOYEES" 
   (	"ID" NUMBER(*,0), 
	"FULL_NAME" VARCHAR2(255 BYTE), 
	"POSITION_ID" NUMBER(*,0), 
	"SALARY" NUMBER(10,2), 
	"DEPARTMENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MYUSER.EMPLOYEES
SET DEFINE OFF;
Insert into MYUSER.EMPLOYEES (ID,FULL_NAME,POSITION_ID,SALARY,DEPARTMENT_ID) values ('1','Иванов Иван Иванович','1','200','2');
Insert into MYUSER.EMPLOYEES (ID,FULL_NAME,POSITION_ID,SALARY,DEPARTMENT_ID) values ('2','Петров Петра Петрович','2','300','1');
Insert into MYUSER.EMPLOYEES (ID,FULL_NAME,POSITION_ID,SALARY,DEPARTMENT_ID) values ('3','Сидоров Сидор Сидорович','3','400','2');
Insert into MYUSER.EMPLOYEES (ID,FULL_NAME,POSITION_ID,SALARY,DEPARTMENT_ID) values ('4','Семнов Семен Семеныч','4','500','3');
--------------------------------------------------------
--  DDL for Index SYS_C008325
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYUSER"."SYS_C008325" ON "MYUSER"."EMPLOYEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "MYUSER"."EMPLOYEES" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "MYUSER"."EMPLOYEES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "MYUSER"."EMPLOYEES" ADD FOREIGN KEY ("POSITION_ID")
	  REFERENCES "MYUSER"."POSITIONDICTIONARY" ("ID") ENABLE;
  ALTER TABLE "MYUSER"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEE_DEPARTMENT_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "MYUSER"."DEPARTMENTS" ("ID") ENABLE;
