--------------------------------------------------------
--  File created - воскресенье-февраля-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table POSITIONDICTIONARY
--------------------------------------------------------

  CREATE TABLE "MYUSER"."POSITIONDICTIONARY" 
   (	"ID" NUMBER(*,0), 
	"POSITIONTITLE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MYUSER.POSITIONDICTIONARY
SET DEFINE OFF;
Insert into MYUSER.POSITIONDICTIONARY (ID,POSITIONTITLE) values ('1','Аналитик');
Insert into MYUSER.POSITIONDICTIONARY (ID,POSITIONTITLE) values ('2','Менеджер');
Insert into MYUSER.POSITIONDICTIONARY (ID,POSITIONTITLE) values ('3','Разработчик');
Insert into MYUSER.POSITIONDICTIONARY (ID,POSITIONTITLE) values ('4','Директор');
--------------------------------------------------------
--  DDL for Index SYS_C008317
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYUSER"."SYS_C008317" ON "MYUSER"."POSITIONDICTIONARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger POSITIONDICTIONARY_BEFOREINSERT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MYUSER"."POSITIONDICTIONARY_BEFOREINSERT" 
BEFORE INSERT ON PositionDictionary
FOR EACH ROW
BEGIN
    SELECT PositionDictionary_Seq.NEXTVAL INTO :NEW.ID FROM dual;
END;
/
ALTER TRIGGER "MYUSER"."POSITIONDICTIONARY_BEFOREINSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table POSITIONDICTIONARY
--------------------------------------------------------

  ALTER TABLE "MYUSER"."POSITIONDICTIONARY" MODIFY ("POSITIONTITLE" NOT NULL ENABLE);
  ALTER TABLE "MYUSER"."POSITIONDICTIONARY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
